branches:
  only:
  - master
  - stable
language: java
env:
  global:
  - secure: cAPA6nGWb0mKXKbupcR3lVD0/Hs2mz6x40Ueq5P7Bv6PlIhypAAR320zdKFBupAsC4368UzIgnXi0NvSpoagGGkn5QDk/6VwYrEW+7mEYjM1eEqj/deFPmCmZmcf+f6l7yUDVC47DJa55CIE/VDykxc6jxYo81fqgT7oTZ7ggXxmdoNUzds7TY2hXgTuAABDfhvRBkIznAk9syAZG7X0B7FtawuIR06aE2arBaL9U2Gh0bYAJzpspWOO3DCfoY2wWdvcLQV07If+Y6VgmNOArmM5uTIDrrxFXtUpkA53xyMAy2GqQSqw/k9OboQtRrsQqJnlAPjBW82zJidOU6T2QBeViNdXZqh3ZJSemwff7Rj6HYWPOgH3IL7VH64r/6A23BRhE0zBXx/0Jms6tbb6Zn2KKcs/eD3+3mf+mDmKnMYwcgKSfSGoRyMpHHse9XSBPm7u1bYC13S9b7w0T7pUXWQBOB76skjJ77jslUMfu5sXH41T6P/SYBhZcPRCU8bfmcbGD0EVNz7E7yrcvlgIsoTKLnJsMR4TFsk5Jvu22qlLqoW2Wda+ezF+vuyZCLsCwIIBOF2ty3CogA0AVhvVBeGtj8pcdjmdXUfcL0x0pTaQ8PE+0d7a+xxaKdTRwAT384n2mnwIj7XeKoi5OsiqoVxvrFDU3blEfVrnWHCRxXw=
  - secure: i0+tWipQFy4vXdDg/lrWUKZrBGXOMDV6zQsGq0twTd3ze2fRRp9Y7HF6f4jjpjs27LDC0BfhuYud8Nusmwn4riibvwYRSOkZmWeNCkVqDL+Yq5rf8uDZLKUnrgAW56d0E1g2DvbgAlrotG/I8qU7NtG+Y4j2Kc9b2T3lVxFFcyXCtytRzUEJF3MfBN18n+V4saD2CHkEtzmCZRHU/CpUZiZnsRISRpZBXMxjBbtQeNlD+ywHnIIkjQ8vK68J1ZEbXs7WKrPHMxitlE37iMiHo4hE0r1bBOTiQxV37hSi0A01TBALat19nbqfOpPkDxyFna7bOrQftWbjo0PpprT0JKuTaf9LNB/bNH5EDChw09y5gGDo/Fr61Nq02178mRSqSAQa5z085aFfKrGPoEULKcBgPnw8FPRr1wbMewjm1bQ7byN9gzO4BohKwkqn7CJwMypeUyhULQcNT3czOE/gErXgazKfp52gnIVypl5fkvOhnMbkgoEaNrePAWd54uVvg4lVFuzoVO0scQyS5m+FQiweT5zFSbbojl/f+ZY/Q0y6YBVZx8RifAJBdbiUvQMaY6Q+t2aGigD6Ay8msnP2xVjEjmK4qhVVLY85y9+EYX4MhMVtwpFqSYzZn7nt08K6ArSw02a9mW/1rTbVtBHfGhx/aTvYfkSayPG3kNjJeak=
  - secure: WygZUfVWuu6pFUjNRLBQcZ9+ggMN4i09Kc4yqSp2LDxFQfZp7sQToVIMUOJv64OmCPeBDSHCnkd4LHY5i3FWyUJmbUizBYvK5iAaumNdkacjHh11zPrWtZl4IDZIDH077UPDzWdqL5sq3s2G9l/xjIyUjHBQoVBifHsssqIp/aMlx1kc2G5BGp1gVeVZ6qkAcDM35aKBxuAdWQJhxT4I2VHTAMbajoE2xU2Bcbb7mTi8nIynXPY8Xt0LDehV3izgOI0kTQhzLoGyvI+FyOqHTUvcM6VavhSgYkrAEWD2k4iIsK/MQtm4ojWVzxNrl770j4IghK5X9Ma2lG+EUL+fXhPvo9yKlGjiQmFnrRWPqQw3LRMDp3svgHa8xXpH5jHeXPPoMeaeXT02f4YpmjPPJnnO1XfhA/cwDcbCBDrNBu3BuyKMk8r5SB8zNgcObbL2xLpGkAKzOuEGe2xUlo6e4wU3CLN5kcixSjcXRDPPskB81mQXrU6lK3ETUcFd/fyT1FyptSytnrnWfGY5b9mnGWRCj7ivmudxzbZQC283DsFg5gZj3SAvEVpSHGcSPnejfZwpHMeokdw5xgiHVeEdrJ1PYaTyL6HEh8JbrSroX+XFVLj592YLxoMU+lNRSIBTegvgoKkl0DldscmpJnY0oUiiGNEPHBK1FsgW9dLg8OE=
  - secure: Nd26Gdj3oa2aquUvftFKc4M6Cms3Vz5aNNuFkUf1W04cbqzoBFLtHDlsVQ1ICaHmJ+seL2Melc9zM45nL3t1iB04hmRi16b8Gi+kUQ/jkBt1RqQC5DssK2Qjd3/vwJCsZAFPXrAxtYeEaWRvoJ5xHWX5XN8CO/XQ+9+/T6wl+NehW8dh+jx94pzBP4mckXLleBjAGX+dIOYmQX8rD7HdsmUi6AOFecJMf1nurzX0OXZ0YMFppUBqgWMsiPmGzM4b7ZVp/a04c3/pmjdQRTQRcXvSGXVpPwmy9Yhpucys1SS/lZmm4jkBX7shC2t6WMyXDv1f5OFRRCGN8ypXLCQCTp0f90iiptJXz9i1KItEX3Bx9OZFgZWI6Pw4XoMT3UEso5SC90YGV4PueJS2Ew3lCq5W1vg94g2xtuxflhxnfzTeusnHigqCwfPVG4UWdYRpMHtFzg7vo56y22LW/5h8At8YWBuaO3sZTMWCdhZDb0t9BRgUITuD5N3GW+ijoL/S5uC5/bZjV0r/HjaayaquePF7U18l/EqlBQYE3xjg9PUGzF0Ux7eTn2wpgBuIm6avHE9XxDkUFo1zUNO2Cyb0s7lRC65ChNEHKn7Nd+T9WDnSffbI5fPE3MVpCXE7corE7jzObCfWfqXN7F13hIX6MnnJ++WDvrNQRM6owRCa/pw=
dist: trusty
jdk:
- oraclejdk12
before_install: 
install:
- mvn install -Dgpg.skip=true -P !build-extras -B -V
before_script: 
script: mvn test -P !build-extras -B
cache:
  directories:
  - "~/.m2/repository"
after_success:
- "./cd/before-deploy.sh"
- "./cd/deploy.sh"
after_failure: 
